export const GENRES = {
  fantasy: {
    id: 'fantasy',
    label: 'Fantasia',
    tagline: 'Forja seu mundo arcano',
    icon: 'ti-wand',
    nav: {
      editor:     { label: 'Editor',         icon: 'ti-feather' },
      characters: { label: 'Personagens',    icon: 'ti-users' },
      races:      { label: 'Raças',          icon: 'ti-shield-half' },
      places:     { label: 'Lugares',        icon: 'ti-map-pin' },
      objects:    { label: 'Objetos',        icon: 'ti-wand' },
      grimoire:   { label: 'Grimório',       icon: 'ti-book-2' },
      dictionary: { label: 'Dicionário',     icon: 'ti-language' },
      finance:    { label: 'Economia',       icon: 'ti-coins' },
      timeline:   { label: 'Linha do Tempo', icon: 'ti-timeline' },
      stats:      { label: 'Estatísticas',   icon: 'ti-chart-bar' },
      settings:   { label: 'Configurações',  icon: 'ti-settings' },
    },
    theme: {
      '--primary':        '#c9a227',
      '--primary-light':  '#e8c95a',
      '--primary-dim':    'rgba(201,162,39,0.22)',
      '--primary-border': 'rgba(201,162,39,0.28)',
      '--accent':         '#534ab7',
      '--accent-deep':    '#26215c',
      '--accent-soft':    '#eeedfe',
      '--accent-mid':     '#7f77dd',
      '--sidebar-bg':     '#13102a',
      '--sidebar-text':   '#c9c3f0',
      '--surface':        '#f4f2fb',
      '--surface-mid':    '#ece8f7',
      '--surface-dark':   '#e4dfef',
      '--text-main':      '#0e0b1a',
      '--muted':          '#6b5fa8',
      '--border':         'rgba(83,74,183,0.18)',
      '--ui-radius':      '6px',
      '--tag-radius':     '12px',
      '--shadow-hard':    'none',
      '--shadow-btn':     'none',
      '--border-w':       '1px',
    },
  },

  scifi: {
    id: 'scifi',
    label: 'Cyberpunk',
    tagline: 'Hackeia o futuro sombrio',
    icon: 'ti-terminal-2',
    nav: {
      editor:     { label: 'Terminal',         icon: 'ti-terminal' },
      characters: { label: 'Hackers',          icon: 'ti-users' },
      races:      { label: 'Facções',          icon: 'ti-shield-half' },
      places:     { label: 'Megacidades',      icon: 'ti-building-skyscraper' },
      objects:    { label: 'Implantes',        icon: 'ti-device-laptop' },
      grimoire:   { label: 'Protocolo',        icon: 'ti-cpu' },
      dictionary: { label: 'Gíria Net',        icon: 'ti-language' },
      finance:    { label: 'Créditos',         icon: 'ti-coins' },
      timeline:   { label: 'Cronologia',       icon: 'ti-timeline' },
      stats:      { label: 'Status',           icon: 'ti-chart-bar' },
      settings:   { label: 'Config',           icon: 'ti-settings' },
    },
    theme: {
      '--primary':        '#ff0066',
      '--primary-light':  '#ff3d82',
      '--primary-dim':    'rgba(255,0,102,0.12)',
      '--primary-border': 'rgba(255,0,102,0.55)',
      '--accent':         '#00ffcc',
      '--accent-deep':    '#003d33',
      '--accent-soft':    '#e0fff9',
      '--accent-mid':     '#00ccaa',
      '--sidebar-bg':     '#080808',
      '--sidebar-text':   '#f0e8ff',
      '--surface':        '#f5f2ed',
      '--surface-mid':    '#ece7de',
      '--surface-dark':   '#dfd8cd',
      '--text-main':      '#0a0605',
      '--muted':          '#8c3059',
      '--border':         'rgba(255,0,102,0.3)',
      '--ui-radius':      '1px',
      '--tag-radius':     '2px',
      '--shadow-hard':    '3px 3px 0 rgba(0,0,0,0.82)',
      '--shadow-btn':     '2px 2px 0 rgba(0,0,0,0.75)',
      '--border-w':       '2px',
    },
  },
}
