export const GENRES = {
  fantasy: {
    id: 'fantasy',
    label: 'Fantasia',
    tagline: 'Forja seu mundo arcano',
    icon: 'ti-wand',
    nav: {
      editor:     { label: 'Editor',         icon: 'ti-feather' },
      characters: { label: 'Personagens',    icon: 'ti-users' },
      races:      { label: 'Raças',          icon: 'ti-shield-half' },
      places:     { label: 'Lugares',        icon: 'ti-map-pin' },
      objects:    { label: 'Objetos',        icon: 'ti-wand' },
      grimoire:   { label: 'Grimório',       icon: 'ti-book-2' },
      dictionary: { label: 'Dicionário',     icon: 'ti-language' },
      timeline:   { label: 'Linha do Tempo', icon: 'ti-timeline' },
      stats:      { label: 'Estatísticas',   icon: 'ti-chart-bar' },
      settings:   { label: 'Configurações',  icon: 'ti-settings' },
    },
    theme: {
      '--primary':        '#c9a227',
      '--primary-light':  '#e8c95a',
      '--primary-dim':    'rgba(201,162,39,0.22)',
      '--primary-border': 'rgba(201,162,39,0.28)',
      '--accent':         '#534ab7',
      '--accent-deep':    '#26215c',
      '--accent-soft':    '#eeedfe',
      '--accent-mid':     '#7f77dd',
      '--sidebar-bg':     '#13102a',
      '--sidebar-text':   '#c9c3f0',
      '--surface':        '#f4f2fb',
      '--surface-mid':    '#ece8f7',
      '--surface-dark':   '#e4dfef',
      '--text-main':      '#0e0b1a',
      '--muted':          '#6b5fa8',
      '--border':         'rgba(83,74,183,0.18)',
    },
  },

  scifi: {
    id: 'scifi',
    label: 'Ficção Científica',
    tagline: 'Expande seu universo',
    icon: 'ti-rocket',
    nav: {
      editor:     { label: 'Editor',         icon: 'ti-feather' },
      characters: { label: 'Tripulação',     icon: 'ti-users' },
      races:      { label: 'Espécies',       icon: 'ti-dna' },
      places:     { label: 'Planetas',       icon: 'ti-planet' },
      objects:    { label: 'Equipamentos',   icon: 'ti-device-gamepad-2' },
      grimoire:   { label: 'Tecnologia',     icon: 'ti-cpu' },
      dictionary: { label: 'Dicionário',     icon: 'ti-language' },
      timeline:   { label: 'Cronologia',     icon: 'ti-timeline' },
      stats:      { label: 'Estatísticas',   icon: 'ti-chart-bar' },
      settings:   { label: 'Configurações',  icon: 'ti-settings' },
    },
    theme: {
      '--primary':        '#00b4d8',
      '--primary-light':  '#48cae4',
      '--primary-dim':    'rgba(0,180,216,0.18)',
      '--primary-border': 'rgba(0,180,216,0.28)',
      '--accent':         '#023e8a',
      '--accent-deep':    '#03045e',
      '--accent-soft':    '#e0f4ff',
      '--accent-mid':     '#0096c7',
      '--sidebar-bg':     '#05101f',
      '--sidebar-text':   '#90caf9',
      '--surface':        '#f0f7ff',
      '--surface-mid':    '#ddeeff',
      '--surface-dark':   '#c8e3fa',
      '--text-main':      '#030d1e',
      '--muted':          '#2a6fa8',
      '--border':         'rgba(0,100,180,0.18)',
    },
  },
}
